//import EventEmitter from 'events'
import Firebase from 'firebase'
import bus from '../bus.js'
import download from '../download'

// ENTER YOUR FIREBASE URL BELOW

// Initialize Firebase
let config = {
    apiKey: "AIzaSyA75zV9V8yUgdHRW1OI9SRCyRUveug8Dxo",
    authDomain: "electron-vue-firebase.firebaseapp.com",
    databaseURL: "https://electron-vue-firebase.firebaseio.com",
    projectId: "electron-vue-firebase",
    storageBucket: "electron-vue-firebase.appspot.com",
    messagingSenderId: "384426481642"
};

let app = Firebase.initializeApp(config)
const db = app.database()

const bookmarksRef = db.ref('bookmarks')

let bookmarks = {}

bookmarksRef.on('value', (snapshot) => {
    bookmarks = snapshot.val()
    bus.$emit('data-updated', bookmarks)
})

// export
export default {

    addBookmark(bookmark) {
        bookmark.title = download.getFilenameFromUrl(bookmark.url);
        
        // Generate a reference to a new location and add some data using push()
        var newBookmarkRef = bookmarksRef.push(bookmark)
        // Get the unique key generated by push()
        var bookmarkId = newBookmarkRef.key
        
        alert("bookmarkId=" +bookmarkId )

        download.downloadFile(bookmarkId, bookmark).then(function(){
            alert("File " + bookmark.title + " succesfully downloaded");
        });
    },
    
    updateProgressBookmark(bookmarkId, received_bytes, total_bytes) {
        
        bookmarksRef.child(bookmarkId).update({
          "received_bytes": received_bytes,
          "total_bytes": total_bytes
        });
    },

    deleteBookmark(bookmarkId) {

        bookmarksRef.child(bookmarkId).remove()
    },

}
